# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: Continuous Integration
    jobs:
      - job: firstJob
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
          
      - job: exploration
        steps:
          - script: ls

      - job: envVariables
        steps:
          - script: echo $(PASSWORD)
      
      - job: secretVariables
        steps:
          - script: echo $(PASSWORD)
            env:
              PASSWORD: $(PASSWORD)